### ISSUE TITLE
Help regarding coloring certain parts

### ISSUE THREAD

**Issue by RexxiToon** [projectcomet64/SPARK#1]
Hello there, name's rexxi and i just wanted to report a issue i've been having recently with the spark editor. So basically if i try to color a body part like for example "overralls top", it just colors the entire overralls instead of only the top, and i have the same issue with "overralls bottom" and etc, also no i did not import in a cc and forgot to convert it to scc

**Comment by GlitchyPSIX** [comment]
Worth noting that SPARK Editor can only work on SPARK models, not the original Mario model or any other custom mod that isn't SPARK compatible

If you need the SPARK model you can find a .CMTP file in the Releases download

**Comment by RexxiToon** [comment]
OH! IM SO SORRY.

Le mer. 29 sept. 2021 à 21:54, GlitchyPSI ***@***.***> a
écrit :

**Comment by RexxiToon** [comment]
Oh btw, sorry if i'm bothering again but what is the name of the .cmtp file?

**Comment by GlitchyPSIX** [comment]
It's the only .cmtp file in the Patches folder from the release folder.
